dscs/urls.py
from django.urls import path
from . import views

app_name = 'dscs'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail' ),
]

pjt1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/',include('boards.urls')),
    path('attendboards/',include('attendboards.urls')),
    path('dscs/',include('dscs.urls')),
    path('scraps/',include('scraps.urls')),
    path('studydiaries/',include('studydiaries.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dscs/models.py
from django.db import models

# Create your models here.
class Algorithm(models.Model):
    title =models.CharField(max_length=20)
    audience = models.IntegerField()
    release_date = models.DateField()
    genre = models.CharField(max_length=30)
    score = models.FloatField()
    poster_url = models.CharField(max_length=50)
    descripthion = models.TextField()

dscs/forms.py
from django import forms
from .models import Algorithm

class AlgorithmForm(forms.ModelForm):
    GENRE_CHOICES = [
        ('test1','테스트1'),
        ('test2','테스트2'),
        ('test3','테스트3')
    ]
    genre = forms.ChoiceField(choices=GENRE_CHOICES)
    score = forms.FloatField(widget=forms.NumberInput(
        #기본태그에 속성 추가
        attrs={
            'min' :0,
            'max':5,
            'step':0.5
        }
    ))
    release_date = forms.DateField(widget=forms.DateInput(
        attrs={
            'type':'date',
        }
    ))
    class Meta:
        model = Algorithm
        fields = '__all__'

dscs/views.py
from django.shortcuts import render,redirect
from .models import Algorithm
from .forms import AlgorithmForm
# Create your views here.
def index(request):
    dscses = Algorithm.objects.all()
    context ={
        'dscses':dscses,
    }
    return render(request, 'dscs/index.html',context)

def create(request):
    
    if request.method =='POST':
        form =AlgorithmForm(request.POST,request.FILES)
        form.save()
        return redirect('dscs:index')
    
    else:
        form = AlgorithmForm()
        context = {
            'form':form
            }
        return render(request,'dscs/create.html',context)

    
def detail(request,pk):
    dscs = pk
    dscs = Algorithm.objects.get(pk=pk) 
    context = {'dscs':dscs,}
    return render(request, 'dscs/detail.html',context)
 

dscs/templates/dscs/create.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<h1>알고리즘 공유 게시판</h1>
<a href="{% url 'dscs:create' %}">글쓰기</a>
<br>
<table class="table">
    <thead>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>날짜</th>
            <th>조회수</th>
        </tr>
    </thead>
    <hr>
    <h1>CREATE</h1>
    <hr>
    <form action="{% url 'dscs:create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="submit">
    </form><hr>
    <a href="{% url 'dscs:index' %}">BACK</a>
</table>


{% endblock content %}

dscs/templates/dscs/detail.html
{% extends 'base.html' %} 
{% block content %}

<h1>DETAIL</h1>
<!-- 
<hr />
<h3>{{dscs.title}}</h3><br>
{{form.as_p}}

<p>Audience : {{dscs.audience}}</p>
<p>Release_date : {{dscs.release_date}}</p>
<p>Genre : {{dscs.genre}}</p>
<p>Score : {{dscs.score}}</p>
<p>poster_url : {{dscs.poster_url }}</p>
<p>descripthion : {{dscs.descripthion}}</p>
<br>
<a href="{% url '' %}">UPDATE</a>
<form action="{% url '' %}" method ="POST">
  {% csrf_token %}
  <input type="submit" value="DELETE">
</form>
<a href="{% url 'dscs:index' %}">BACK</a> -->

{% endblock content %}

dscs/templates/dscs/index.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<h1>알고리즘 공유 게시판</h1>
<a href="{% url 'dscs:create' %}">글쓰기</a>
<br>
<table class="table">
    <thead>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>날짜</th>
            <th>조회수</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <!-- <th>1번</th> --> 
            {% for dscs in dscses %}
            <a href="{% url 'dscs:detail' dscs.pk  %}">{{dscs.title}}</a><br>
            <p>{{dscs.score}}</p>
        </tr>
    </tbody>
</table>


{% endblock content %}