accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup,name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<pk>/', views.detail, name='detail'),
    path('<pk>/delete', views.delete, name='delete'),
    path('<pk>/update', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<pk>/like',views.like, name='like'),
]

dscs/urls.py
from django.urls import path
from . import views

app_name = 'dscs'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail' ),
]

pjt1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/',include('boards.urls')),
    path('attendboards/',include('attendboards.urls')),
    path('dscs/',include('dscs.urls')),
    path('scraps/',include('scraps.urls')),
    path('studydiaries/',include('studydiaries.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    writer_nickname = models.CharField(max_length=300)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    reads = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.id}번째글 - {self.title}'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

boards/forms.py
from django import forms
from .models import Article, Comment

# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=30)
#     content = forms.CharField(widget=forms.Textarea)

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        # fields = '__all__'
        exclude = ('user','writer_nickname','like_users')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ('article', 'user',)

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
import logging
from django.contrib.auth.signals import user_logged_in, user_logged_out, user_login_failed
from django.dispatch import receiver

log = logging.getLogger(__name__)

@receiver(user_logged_in)
def user_logged_in_callback(sender, request, user, **kwargs):
    ip = request.META.get('REMOTE_ADDR')
    log.debug('login user: {user} via ip: {ip}'.format(
        user=user,
        ip=ip,
    ))
@receiver(user_logged_out)
def user_logged_out_callback(sender, request, user, **kwargs): 
    ip = request.META.get('REMOTE_ADDR')
    log.debug('logout user: {user} via ip: {ip}'.format(
        user=user,
        ip=ip
    ))

@receiver(user_login_failed)
def user_login_failed_callback(sender, credentials, **kwargs):
    log.warning('login failed for: {credentials}'.format(
        credentials=credentials,
    ))

def like(request,pk):  #좋아요
    article = get_object_or_404(Article,pk=pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
        return redirect('boards:detail',article.pk)
    else:
        article.like_users.add(request.user)
        return redirect('boards:detail',article.pk)

# Create your views here.
def index(request):
    articles = Article.objects.all()
    articles = articles.order_by('-created_at')
    page = request.GET.get('page')
    paginator = Paginator(articles,10)
    # paginator = Paginator(content_list,10)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page =1
        page_obj = paginator.page(page)
    except EmptyPage:
        page = paginator.num_pages
        page_obj = paginator.page(page)

    #정렬기능
    # sort = request.GET.get('sort','')
    # if sort =='likes':
    #     content_list = Content.objects.all().order_by('-like_count','-date')
    # elif sort == 'comments':
    #     content_list = Content.objects.all().order_by('-comment_count','-date')
    # else:
    #     content_list = Content.objects.all().order_by('-date')

    # page = request.GET.get('page','')
    # posts = paginator.get_page(page)
    # board = Board.objects.all()
    
    context = {
        'articles' : articles,
        'page_obj': page_obj,
        'paginator' : paginator,
        
        
    }
    return render(request,'boards/index.html',context)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    comment_view=Comment.objects.filter(article=pk)
    context = {
        'article': article,
        'comment_form':comment_form,
        'comment_view':comment_view,
    }
    
    article.reads += 1
    article.save()
    return render(request, 'boards/detail.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('boards:detail', article.pk)
    else:
        form = ArticleForm()
    context = {'form': form,}
    return render(request, 'boards/create.html', context)

@require_POST
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('boards:index')

def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('boards:detail', pk=article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {'form': form, 'article': article}
    return render(request, 'boards/update.html', context)

@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
        return redirect('boards:detail', article.pk)
    return redirect('accounts:login')


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('boards:detail', article_pk)

boards/templates/boards/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<h1>CREATE</h1>
<hr>
<form action="{% url 'boards:create' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="작성하기">
</form>
<a href="{% url 'boards:index' %}">글 목록</a>
{% endblock content %}

boards/templates/boards/detail.html
{% extends 'base.html' %} 

{% block content %}
  <h1>DETAIL</h1>
  작성자 : {{ article.user }}<br>
  글 제목 : {{article.title}} | 조회수 : {{ article.reads}}<br>
  작성 시간 : {{article.created_at}}
  <hr>
  <p>글 내용 : {{article.content}}</p>
  {% if article.image %}
  <img src="{{article.image.url}}" alt="{{article.image}}" style="width: 600px;">
  {% endif %}
  <hr>
  <a href="{% url 'boards:index' %}" class="btn btn-success">글 목록</a>
  {% if article.user == request.user %}
  <form action="{% url 'boards:delete' article.pk %}" class="btn btn-danger" method="POST">삭제하기</form>
  {% endif %}
  
  <!-- 좋아요 -->
  {% if request.user in article.like_users.all %}
  <a href="{% url 'boards:like' article.pk %}">
  <i class="fas fa-heart fa-lg animated hinge delay-1s" style="color: red;">취소하기</i></a>
  
  {% else %}
  <a href="{% url 'boards:like' article.pk %}">
    <i class="far fa-heart fa-lg animated infinite bounce delay-1s" style="color: gray;">좋아요</i>
</a>
  {% endif %}
  <p>{{ article.like_users.count }}명이 좋아합니다. </p>
  <hr>

<!--이하 댓글창-->

<h4>댓글 목록</h4>

<!--read-->
{% if comments %}
  <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
{% endif %}
<ul>
  {% for comment in comment_view %}
  <hr>
  <p>{{ comment.user }}</p>
  <p>{{ comment.content }}</p>
  <!--delete-->
  {% if user == comment.user %}
  <form action="{% url 'boards:comments_delete' article.pk comment.pk %}" method="POST" class="d-inline">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
{% endif %}
  <hr>
  {% endfor %}
</ul>

<hr>

<!--create-->
{% if request.user.is_authenticated %}
    <p>로그인됨</p>

  <form action="{% url 'boards:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit">
  </form>
{% else %}
  <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
{% endif %}

<!--이상 댓글창-->
{% endblock content %}

boards/templates/boards/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<hr>
<a href="{% url 'boards:create' %}">작성하기</a>
<!-- 게시글 정렬 -->
<form method="GET" action="{% url 'boards:index' %}">
  <div class="col-4">
    <select name="sort" id="sort">
      <option value="recently" id="recently">최신순</option>
      <option value="likes" id="likes">좋아요순</option>
      <option value="comments" id="comments">댓글순</option>
    </select>
    <button class="btn btn-primary" type="submit" value="">정렬</button>
  </div>
<hr>
<div class="container" style="margin-bottom:100px">
{% for article in page_obj%}
    <div class="card mb-5" style="max-width: 1400px; max-height:500px;">
      <div class="row g-0">
        <div class="col-md-4">
          {% if article.image %}
          <img src="{{ article.image.url }}" class="img-fluid rounded-start" alt="{{article.image}}">
          {% else %}
          <img src="{% static 'img_default.png' %}" alt="img_default">
          {% endif %}
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"></h5>
            <p class="card-text" style="display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 3; overflow: hidden;"><a href="{% url 'boards:detail' article.pk %}">{{ article.content }}</a></p>
            <span class="text-muted"><small class="text-muted">작성 시간 : {{article.created_at}}</small></span>
              <!--<small class="text-muted">작성 시간 : {{article.created_at}}</small></p>-->
            <p>작성자 : {{article.user}}</p>
          </div>
        </div>
      </div>
    </div>

{% endfor %}
</div>
<!--pagination-->
<nav aria-label="... ">
  <ul class="pagination" style="position:relative; justify-content: center; bottom:0;" >
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
    </li>
    {% for page in paginator.page_range  %}
        <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
    {% endfor %}
    <li class="page-item">
      <a class="page-link" href="#">Next</a>
    </li>
  </ul>
</nav>

{% endblock content %}

boards/templates/boards/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<h1>UPDATE</h1>
<hr>
<a href="{% url 'boards:index' %}" class="btn btn-success">글 목록</a>
<hr>
<form action="{% url 'boards:update' article.pk %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  <div class="hello">
    <input type="reset" value="초기화">
    <input type="submit" value="수정하기">
  </div>
</form>

{% endblock content %}`