accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup,name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
]

attendboards/urls.py
from django.urls import path
from . import views

app_name = 'attendboards'
urlpatterns = [
    path('',views.index, name = 'index'),
    path('write/', views.write, name = 'write'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<pk>/', views.detail, name='detail'),
    path('<pk>/delete', views.delete, name='delete'),
    path('<pk>/update', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<pk>/like',views.like, name='like'),
]

dscs/urls.py
from django.urls import path
from . import views

app_name = 'dscs'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail' ),
]

pjt1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/',include('boards.urls')),
    path('attendboards/',include('attendboards.urls')),
    path('dscs/',include('dscs.urls')),
    path('scraps/',include('scraps.urls')),
    path('studydiaries/',include('studydiaries.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scraps/urls.py
from django.urls import path
from . import views

app_name = 'scraps'
urlpatterns = [
    path('', views.index, name='index'),
    path('crud/', views.crud, name='crud')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous"> 
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style='padding-top:100px'>

  
    <!--blog_header-->
<div class="container">
  <nav class="navbar navbar-dark bg-dark fixed-top">
    <div class="container-fluid ">
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-start text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">
            <img src="{% static 'ssafy.png' %}" alt="ssafy"></h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'studydiaries:index' %}">스터디 일지</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'scraps:index' %}">스크랩</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'attendboards:index' %}">방명록</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">스케줄</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:update' %}">회원정보 수정</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
      <a class="navbar-brand" href="{% url 'boards:index' %}">대전 1반 SSAFY 화이팅</a>
      <div>
        <form class="d-flex mt-0" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-success " type="submit">Search</button>
        </form>
      </div>
    </div>
</nav>
    {% block content %}
    {% endblock content %}
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html>